### ISSUE TITLE
Wiki instructions for BOOT and EN are swapped

### ISSUE THREAD

**Issue by mightymos** [hwstar/9-Valve-Sprinkler-Controller#1]
https://github.com/hwstar/9-Valve-Sprinkler-Controller/wiki/Uploading-the-Firmware

As best I can tell the wiki instructions should read that first both EN and BOOT switches should be held, and then while keeping the BOOT switch depressed, release the EN switch. One second after the red LED lights, release the BOOT switch.

This procedure seems to work on my board and I guess it makes sense because we want the boot switch asserted while exiting reset mode to allow entering bootloader.

**Comment by hwstar** [comment]
The instructions have been corrected. Thanks for finding this!
